### PR TITLE
[DOCS] Adds low-level subsection from ES repo to TOC

### PR DESCRIPTION
**Pull request by szabosteve**
## Overview

This PR adds the content of the `docs/java-rest/low-level/` folder in the ES repo to the Elasticsearch Java API Client book.

### CODE REVIEW

**Review by swallez — APPROVED** [review]

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by gtback** [comment]
Woo hoo! Glad this finally passed and got merged in!

**Comment by szabosteve** [comment]
Me too! Thanks for all the help, Greg!

**Pull request merged**
