### PR TITLE
Add support for WORKFLOW and user/group IDs to assemble job

### PR DESCRIPTION
**Pull request by sethmlarson**
Adapted https://github.com/elastic/elasticsearch-py/pull/2021 and https://github.com/elastic/elasticsearch-py/pull/2018 to elasticsearch-java as a starting point for DRA support.

Things I changed and outstanding questions:

- Changed `USER_ID` and `GROUP_ID` to `BUILDER_UID` and `BUILD_GID` to match other Dockerfiles. I'm not sure if these had any effect somewhere hidden, maybe something with Gradle?
- Added a patch version to `version.txt`, when this is backported to 8.5 branch this value will need to be updated. I'm also not certain if this has impacts on the client?
- I didn't change anything with what is built into `.ci/output`. In particular [we aren't doing anything with `.ci/output/repository/`](https://github.com/elastic/infra/pull/37260) and I'm not sure if we need to be?

Tested with the following to emulate how assemble would behave when run under DRA:

#### Snapshot

```
$ STACK_VERSION=$(cat config/version.txt) WORKFLOW=snapshot ./.ci/make.sh assemble $STACK_VERSION

$ ls .ci/output/release/
dependencies.csv
elasticsearch-java-8.6.0-SNAPSHOT-javadoc.jar
elasticsearch-java-8.6.0-SNAPSHOT-sources.jar
elasticsearch-java-8.6.0-SNAPSHOT.jar
elasticsearch-java-8.6.0-SNAPSHOT.pom
```

#### Staging

```
$ STACK_VERSION=$(cat config/version.txt) WORKFLOW=staging ./.ci/make.sh assemble $STACK_VERSION

$ ls .ci/output/release/
dependencies.csv
elasticsearch-java-8.6.0.jar
elasticsearch-java-8.6.0-javadoc.jar
elasticsearch-java-8.6.0.pom
elasticsearch-java-8.6.0-sources.jar
```

### CODE REVIEW

**Review by picandocodigo — COMMENTED** [review]
The `USER_ID` and `GROUP_ID` in the Dockerfile are -as far as I understand- just for the release manager to have permissions on the artifacts produced by `make.sh assemble`. Hopefully it doesn't affect anything else using the Dockerfile, but Sylvain will know better.

I can't comment on the version.txt change, but I think Sylvain was going to integrate this with automating the bump action.

The generated artifacts look like they're ok, the DRA artifact set [will look for a maven dir](https://github.com/elastic/infra/blob/c045ca711ce426f6c581dfa312da4b66d3541160/cd/release/release-manager/project-configs/master/elasticsearch-java.gradle#L22-L24) in `.ci/output/release`. So I guess the `pom` file and the rest of the files are enough and no generation of a compressed file is needed, but yeah Sylvain will know better.

**Review by swallez — COMMENTED** [review]
Changes to uid/gid look good.

Wondering about the version though: in the context of a DRA build, what is the version when `make.sh assemble <version>` is called? Where does it come from?

The Gradle build uses this value when set, and otherwise falls back to the version in `config/version.txt`.

**Comment by swallez** [comment]
I've added a commit that
- lazily creates the group and user in the Dockerfile (the group coming from my machine already exists in the base image)
- makes the Dockerfile more minimal: we don't care about user/group being `system` and the user doesn't need a home directory
- implements the `bump` command, that just writes to `config/version.txt`.

> the pom file and the rest of the files are enough and no generation of a compressed file is needed

This is what we provide currently to the release manager. If the DRA releaser behaves the same, that should be all that is needed. And indeed `.ci/output/repository` is not needed (I need to clean this up).

**Review by swallez — APPROVED** [review]
LGTM with my additional commit ;-)

Do not pay attention to the failing "Code style and license headers" check, it'll be fixed in another PR.

**Review by sethmlarson — COMMENTED** [review]
The extra changes LGTM after testing locally. I especially enjoy the simple implementation of the bump task :) Once this is merged I'll update the `version.txt` to `8.5.0` as well.

**Review by picandocodigo — APPROVED** [review]

**Comment by swallez** [comment]
Should we backport to 7.17 or will it stay on Unified Release Manager?

**Comment by sethmlarson** [comment]
Yeah that's the plan! We're waiting to merge the rest of the backports until we get a successful status on the `main` branch.

**Pull request merged**
