### PR TITLE
Reorder key-values in meta header to match other clients #334

### PR DESCRIPTION
**Pull request by Ankit-Khachane**
corrected the sequence for the CLIENT META VALUE sequence as mentioned in the description from the following link

Closes https://github.com/elastic/elasticsearch-java/issues/334

### CODE REVIEW

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by sethmlarson** [comment]
@Ankit-Khachane Btw, in the future you can "link" a GitHub issue to close as soon as a PR is merged by adding "Closes #XYZ" where `XYZ` is the issue number you want to link.

**Comment by Ankit-Khachane** [comment]
Hi, @sethmlarson can you tell me when this PR changes will be merged in the main branch?

**Review by swallez — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
