### PR TITLE
Updates to installation doc with helidon framework notes

### PR DESCRIPTION
**Pull request by ksurendra**
Added notes mentioning that the dependency `jakarta.json:jakarta.json-api:2.0.1` needs to be explicitly added to projects built with other frameworks like [Helidon](https://helidon.io) and not only Spring Boot.

Else users will see the same exception at runtime: `java.lang.ClassNotFoundException: jakarta.json.spi.JsonProvider`.

### CODE REVIEW

**Comment by ksurendra** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [1a35f6c](https://github.com/elastic/elasticsearch-java/commit/1a35f6c720727bf9d40b3f7521fcb8a3eaf1db93)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Completed doc sign on 3/30/2022

**Comment by swallez** [comment]
@ksurendra for my understanding, can you explain what happens in Helidon without the dependency added? Is it forced into a different version as with the Spring plugin? Does it lead to `ClassNotFoundException`?

**Comment by ksurendra** [comment]
> @ksurendra for my understanding, can you explain what happens in Helidon without the dependency added? Is it forced into a different version as with the Spring plugin? Does it lead to `ClassNotFoundException`?

@swallez without the dependency users will see a exception at runtime: `java.lang.ClassNotFoundException: jakarta.json.spi.JsonProvider`

**Comment by swallez** [comment]
Ok, thanks. This looks like the exact same problem as with Spring.

The CLA check still fails. Did you use the same GitHub account when signing it? If yes, I'll reach out to our infra team to understand why it keeps failing.

**Comment by swallez** [comment]
@ksurendra the docs have been heavily restructured, and I also refactored the installation document to explain this issue in a more framework-independent way while still mentioning Spring Boot and Helidon.

I will therefore close this PR, which has been superseded by PR #265 (and has been [published on the website](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/master/installation.html)). Thanks for the heads up about Helidon!

**Pull request closed without merging**
