### PR TITLE
Disable stored fields

### PR DESCRIPTION
**Pull request by valasatava**
This PR is raised to address https://github.com/elastic/elasticsearch-java/issues/701

### CODE REVIEW

**Comment by josemduarte** [comment]
Same issue was also reported in #680 and #700

**Comment by pmakari** [comment]
Any updates on this? When do you plan to review/merge this PR. 
 This is a blocker for us and we cannot finish the migration to Java API Client. 
 
 cc: @valasatava @josemduarte @swallez

**Comment by dmyersturnbull** [comment]
Hi @swallez! If you have the chance, could you take a look at this PR? It looks like an easy merge, and it fixes issue #701, which is a blocker for us. Others reported the same problem in issues #680 and #700.

**Comment by l-trotta** [comment]
recently fixed! will be part of the next release

**Pull request closed without merging**
